// Baseline snapshot of the schema as it existed before the migrations system was introduced.
// Every statement is IF NOT EXISTS, so on an existing database this is a no-op;
// on a fresh database it creates the original tables. Do not edit - add a new migration instead.
const statements = [
  "CREATE TABLE IF NOT EXISTS `alumni_master` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `enrollment` varchar(20) NOT NULL,\n  `full_name` varchar(100) NOT NULL,\n  `dob` date NOT NULL,\n  `course` varchar(30) NOT NULL,\n  `branch` varchar(50) NOT NULL,\n  `passout_year` year NOT NULL,\n  `college_email` varchar(255) DEFAULT NULL,\n  `mobile` varchar(15) DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `enrollment` (`enrollment`),\n  UNIQUE KEY `college_email` (`college_email`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `student_master` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `enrollment` varchar(20) NOT NULL,\n  `full_name` varchar(100) NOT NULL,\n  `dob` date NOT NULL,\n  `course` varchar(30) NOT NULL,\n  `branch` varchar(50) NOT NULL,\n  `admission_year` year NOT NULL,\n  `college_email` varchar(255) DEFAULT NULL,\n  `mobile` varchar(15) DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `enrollment` (`enrollment`),\n  UNIQUE KEY `college_email` (`college_email`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `users` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `enrollment` varchar(20) NOT NULL,\n  `email` varchar(150) NOT NULL,\n  `email_verified` tinyint(1) NOT NULL DEFAULT '0',\n  `password_hash` varchar(255) NOT NULL,\n  `role` enum('STUDENT','ALUMNI','ADMIN') NOT NULL,\n  `status` enum('ACTIVE','PENDING','BLOCKED','REJECTED') NOT NULL DEFAULT 'PENDING',\n  `failed_login_attempts` int NOT NULL DEFAULT '0',\n  `locked_until` datetime DEFAULT NULL,\n  `last_login` datetime DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `verified_by` bigint DEFAULT NULL,\n  `verified_at` datetime DEFAULT NULL,\n  `rejection_reason` varchar(255) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `enrollment` (`enrollment`),\n  UNIQUE KEY `uq_email` (`email`),\n  KEY `fk_verified_by` (`verified_by`),\n  CONSTRAINT `fk_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `profiles` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `full_name` varchar(100) NOT NULL,\n  `profile_photo` varchar(500) DEFAULT NULL,\n  `bio` varchar(500) DEFAULT NULL,\n  `location` varchar(100) DEFAULT NULL,\n  `linkedin_url` varchar(500) DEFAULT NULL,\n  `github_url` varchar(500) DEFAULT NULL,\n  `portfolio_url` varchar(500) DEFAULT NULL,\n  `resume_url` varchar(500) DEFAULT NULL,\n  `company` varchar(150) DEFAULT NULL,\n  `designation` varchar(150) DEFAULT NULL,\n  `experience_years` decimal(4,1) DEFAULT NULL,\n  `interests` varchar(500) DEFAULT NULL,\n  `career_goals` varchar(500) DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `profile_photo_public_id` varchar(255) DEFAULT NULL,\n  `batch_year` int DEFAULT NULL,\n  `branch` varchar(100) DEFAULT NULL,\n  `current_year` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `user_id` (`user_id`),\n  CONSTRAINT `fk_profile_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `profile_skills` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `profile_id` bigint NOT NULL,\n  `skill` varchar(100) NOT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_profile_skill` (`profile_id`,`skill`),\n  CONSTRAINT `fk_profile_skill_profile` FOREIGN KEY (`profile_id`) REFERENCES `profiles` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `profile_projects` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `profile_id` bigint NOT NULL,\n  `title` varchar(150) NOT NULL,\n  `description` text,\n  `project_url` varchar(500) DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_profile_project_profile` (`profile_id`),\n  CONSTRAINT `fk_profile_project_profile` FOREIGN KEY (`profile_id`) REFERENCES `profiles` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `otp_verifications` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `otp_hash` varchar(255) NOT NULL,\n  `purpose` enum('LOGIN','REGISTER','RESET_PASSWORD') NOT NULL,\n  `expires_at` datetime NOT NULL,\n  `attempts` int NOT NULL DEFAULT '0',\n  `is_used` tinyint(1) NOT NULL DEFAULT '0',\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_otp_user` (`user_id`),\n  CONSTRAINT `fk_otp_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `password_resets` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `token_hash` varchar(255) NOT NULL,\n  `expires_at` datetime NOT NULL,\n  `used_at` datetime DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_password_reset_user` (`user_id`),\n  CONSTRAINT `fk_password_reset_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `user_sessions` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `token_hash` varchar(255) NOT NULL,\n  `device_info` varchar(255) DEFAULT NULL,\n  `ip_address` varchar(45) DEFAULT NULL,\n  `expires_at` datetime NOT NULL,\n  `revoked_at` datetime DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_session_user` (`user_id`),\n  CONSTRAINT `fk_session_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `connections` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `sender_id` bigint NOT NULL,\n  `receiver_id` bigint NOT NULL,\n  `status` enum('PENDING','ACCEPTED','REJECTED','CANCELLED','REMOVED') NOT NULL DEFAULT 'PENDING',\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_connection_sender` (`sender_id`),\n  KEY `fk_connection_receiver` (`receiver_id`),\n  CONSTRAINT `fk_connection_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `users` (`id`),\n  CONSTRAINT `fk_connection_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`),\n  CONSTRAINT `chk_connection_users` CHECK ((`sender_id` <> `receiver_id`))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `conversations` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_one_id` bigint NOT NULL,\n  `user_two_id` bigint NOT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `user_one_id` (`user_one_id`,`user_two_id`),\n  KEY `user_two_id` (`user_two_id`),\n  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`user_one_id`) REFERENCES `users` (`id`),\n  CONSTRAINT `conversations_ibfk_2` FOREIGN KEY (`user_two_id`) REFERENCES `users` (`id`),\n  CONSTRAINT `conversations_chk_1` CHECK ((`user_one_id` <> `user_two_id`))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `messages` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `conversation_id` bigint NOT NULL,\n  `sender_id` bigint NOT NULL,\n  `content` text NOT NULL,\n  `read_at` timestamp NULL DEFAULT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `is_read` tinyint(1) NOT NULL DEFAULT '0',\n  PRIMARY KEY (`id`),\n  KEY `sender_id` (`sender_id`),\n  KEY `idx_messages_conversation_read` (`conversation_id`,`is_read`,`sender_id`),\n  CONSTRAINT `messages_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`),\n  CONSTRAINT `messages_ibfk_2` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `posts` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `user_id` bigint NOT NULL,\n  `content` text,\n  `status` enum('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `deleted_at` timestamp NULL DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `fk_post_user` (`user_id`),\n  CONSTRAINT `fk_post_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `post_media` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `post_id` bigint NOT NULL,\n  `media_url` varchar(500) NOT NULL,\n  `media_type` enum('IMAGE','VIDEO') NOT NULL,\n  `public_id` varchar(255) NOT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_post_media_post` (`post_id`),\n  CONSTRAINT `fk_post_media_post` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `post_likes` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `post_id` bigint NOT NULL,\n  `user_id` bigint NOT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_post_like` (`post_id`,`user_id`),\n  KEY `fk_post_like_user` (`user_id`),\n  CONSTRAINT `fk_post_like_post` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`),\n  CONSTRAINT `fk_post_like_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
  "CREATE TABLE IF NOT EXISTS `post_comments` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `post_id` bigint NOT NULL,\n  `user_id` bigint NOT NULL,\n  `content` text NOT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  KEY `fk_post_comment_post` (`post_id`),\n  KEY `fk_post_comment_user` (`user_id`),\n  CONSTRAINT `fk_post_comment_post` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`),\n  CONSTRAINT `fk_post_comment_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci"
];

module.exports = {
    async up(conn) {
        for (const sql of statements) {
            await conn.query(sql);
        }
    },
    // intentionally no down(): dropping the baseline would destroy all data
};
